[package]
name = "rusty-dawg"
version = "0.1.0"
authors = ["lambdaviking"]
repository = "https://github.com/viking-sudo-rm/rusty-dawg"
edition = "2015"

[dependencies]
bincode = "1.3.3"
bit-struct = "0.3.2"
bitvec = "1.0.1"
clap = { version = "4.3.8", features = ["derive"] }
fixedbitset = "0.4.2"
kdam = "0.3.0"
petgraph = "0.6.3"
serde = "1.0.163"
serde_json = "1.0.96"
memory-stats = "1.1.0"
substring = "1.4.5"
tempfile = "3.6.0"
test-temp-file = "0.1.2"
type-layout = "0.2.0"
ux = "0.1.5"
anyhow = "1.0"
tokenizers = "0.13.3"
unicode-segmentation = "1.10"
openssl = { version = "0.10", features = ["vendored"] }
